language: node_js
node_js:
- '6'
before_script:
- npm install -g mocha
services:
- mongodb
script:
- npm test
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIBEZAIGAGGLFT5RA
  secret_access_key:
    secure: WAedXUXsc4jwZhLp7gLxbGM1R2uXvG91FsWuh/cKJK2jkBdBOze2kTBEXRzdoSCtnf21ZDKsiMqVKUpkG+GxJzCP+2p7nfPCIBql4ySAA7fHktsMloH3g9rmZXCF7H8WRyRwVnx465ckRNIa1Wt7XBqFc+dXlWlBityfIgOCcinDF2ec5IbINENY8Ldj3wL3TJd9KshmJuxTUBwKxR5FchGAzkKE2qtYfzOmUZWIn/LshLH6AoKX77CLFbP1Eo9Kx6LFisv97PgijuEQfN5tBG80yjsVSebfdSPwXP4/eUrbRLP3liRYYU4BJWfqND5RYAWOuEyLklLhRMywE87H/HV1zLqaQxWtssLQKWiFPSEfcHMsCqKgrhuFTsNawsbmtbBh673So9FLf8hYYaNDELnz1Z3H+0qkvHvZgtCp+uBoGIESHrKsHmpo0XyFvKPlmfExJni+cbR1c2+Jbni/5KZ96hwHkePyQYhnAnF7fj+66EA3buBQBTkb6M6EANGSdQ1gXYPMvmEbZLAYt38OENibyLHb+5iLyzMcmqraPyCjlsol8vJrTSez3UQok7uT7Odi3vhiLnVFlsIgxlCdVe1OIUQsPsq5VErdd2vpMudpfjF/g45t/tNwZQAoEiuuQxU9I/3MCxYHiPlEbhjnPY4L8Oe52+TkM0PtbAc1CkY=
  region: eu-central-1
  app: grandma-care-server
  env: grandma-care-server-prod
  on:
    repo: arfanizar/grandma-care-server
